### ISSUE TITLE
Console pod CrashLoopBackOff: 'secrets "webconsole-serving-cert" not found'

### ISSUE THREAD

**Issue by naumannt** [openshift/origin-web-console-server#37]
I used the AWS playbooks located [here](https://github.com/openshift/openshift-ansible/tree/release-3.9/playbooks/aws) to set up an openshift cluster; I just installed the master node and wanted to make sure everything is running fine. The external master ELB leads to the error message detailed in [this issue](https://github.com/openshift/origin/issues/18207). 
I therefore tried to install the console from the template linked in this repo's README.

Used configuration file:
```
apiVersion: webconsole.config.openshift.io/v1
kind: WebConsoleConfiguration
clusterInfo:
  consolePublicURL: https://ec****.eu-central-1.compute.amazonaws.com:8443/console/
  loggingPublicURL: ""
  logoutPublicURL: ""
  masterPublicURL: https://ec****.eu-central-1.compute.amazonaws.com:8443
  metricsPublicURL: ""
extensions:
  scriptURLs: []
  stylesheetURLs: []
  properties: null
features:
  inactivityTimeoutMinutes: 0
  clusterResourceOverridesEnabled: false
servingInfo:
  bindAddress: 0.0.0.0:8443
  bindNetwork: tcp4
  certFile: /root/certs/tls.crt
  clientCA: ""
  keyFile: /root/certs/tls.key
  maxRequestsInFlight: 0
  namedCertificates: null
  requestTimeoutSeconds: 0
```

It's difficult to get a clear error message from the pod, it apparently just prints the config file when I do 'oc logs -f <podname>'.
Event log: 
```
Events:
  Type     Reason                 Age                 From                                                     Message
  ----     ------                 ----                ----                                                     -------
  Normal   Scheduled              28m                 default-scheduler                                        Successfully assigned webconsole-5d4cfd95db-7m49z to ip-****.eu-central-1.compute.internal
  Normal   SuccessfulMountVolume  28m                 kubelet, ip-****.eu-central-1.compute.internal  MountVolume.SetUp succeeded for volume "webconsole-config"
  Normal   SuccessfulMountVolume  28m                 kubelet, ip-****.eu-central-1.compute.internal  MountVolume.SetUp succeeded for volume "webconsole-token-2spzk"
  Warning  FailedMount            28m                 kubelet, ip-****.eu-central-1.compute.internal  MountVolume.SetUp failed for volume "serving-cert" : secrets "webconsole-serving-cert" not found
  Normal   SuccessfulMountVolume  28m                 kubelet, ip-****.eu-central-1.compute.internal  MountVolume.SetUp succeeded for volume "serving-cert"
  Normal   Created                28m (x4 over 28m)   kubelet, ip-****.eu-central-1.compute.internal  Created container
  Normal   Started                28m (x4 over 28m)   kubelet, ip-****.eu-central-1.compute.internal  Started container
  Normal   Pulled                 27m (x5 over 28m)   kubelet, ip-****.eu-central-1.compute.internal  Container image "openshift/origin-web-console:latest" already present on machine
  Warning  BackOff                3m (x119 over 28m)  kubelet, ip-****.eu-central-1.compute.internal  Back-off restarting failed container
```

Why is there no clearer documentation on this? It's a pretty big change from earlier versions (the console not coming with the master by default anymore).

**Comment by naumannt** [comment]
For some unknown reason (no changes) I can now see a clearer error message in the pod:
```
Error: AssetConfig.webconsole.config.openshift.io "" is invalid: [config.servingInfo.certFile: Invalid value: "/root/certs/tls.crt": could not read file: stat /root/certs/tls.crt: no such file or directory, config.servingInfo.keyFile: Invalid value: "/root/certs/tls.key": could not read file: stat /root/certs/tls.key: no such file or directory]
```
I'm not entirely sure why this is the case; the certs are in the folders. Is it because the pod is not able to access the file system the way I expected? How do I put the certs in there if not via a path?
(again documentation for the config file would be great)

**Comment by spadgett** [comment]
@naumannt Can you include the last part of the output from Ansible you saw if you still have it? It should print a lot of debugging info when the console install fails, which would tell us what went wrong.

The issue you pointed to was because users were installed an earlier OpenShift version with playbooks from the master branch. You're probably hitting another problem. It would be good to understand what went wrong in case it's a bug in the AWS playbooks.

You should not need to install the template manually... It is possible to just run the console playbook with your inventory file if you need.

> I'm not entirely sure why this is the case; the certs are in the folders. Is it because the pod is not able to access the file system the way I expected? How do I put the certs in there if not via a path?
(again documentation for the config file would be great)

This is not a property you should need to change... These certs are not what users see in the browser.

Since the console is running in a pod, it won't be able to access files on the master filesystem. It's using a generated cert that is mounted in from a secret. Can you try to revert the changes you made to those paths and apply the template again?

**Comment by naumannt** [comment]
I think the Master software installation ran without any problems, so I have no logs saved from that installation. I just noticed that the console is missing when I checked it after.
I don't really have an inventory file (the referenced playbook folder builds an inventory dynamically based on AWS resources afaik). 
Will try running the console template again with original paths asap.

**Comment by naumannt** [comment]
Finally got around to running the template with default paths; only thing I changed from the original configuration are master and console hostname.

Result stays the same:
```
F0514 09:44:11.667874       1 console.go:35] unable to load server certificate: open /var/serving-cert/tls.crt: permission denied
```

**Comment by spadgett** [comment]
@naumannt Can you see if this fixes it for you?

https://access.redhat.com/solutions/3428351

@sdodson fyi

**Comment by naumannt** [comment]
I used `oc adm policy add-scc-to-user privileged system:serviceaccount:openshift-web-console:webconsole`. Not entirely sure if that worked because I can't confirm it with `oc describe sa webconsole`(it doesn't say anything about privileged access).
Still crash-looping with same error message, though.

**Comment by spadgett** [comment]
Yeah, the console shouldn't need privileged access. Apparently there is a bug in the install where the service account is incorrectly added to the anyuid SCC. Can you try to remove anyuid and use restricted instead? (See link above.)

**Comment by naumannt** [comment]
Sorry, misunderstood the linked solution, tried ```oc adm policy remove-scc-from-user privileged system:serviceaccount:openshift-web-console:webconsole``` 
and 
```oc adm policy remove-scc-from-user anyuid system:serviceaccount:openshift-web-console:webconsole```
 and 
```oc adm policy add-role-to-user restricted system:serviceaccount:openshift-web-console:webconsole``` 
now; sadly unchanged:
```
F0514 12:43:12.672295       1 console.go:35] unable to load server certificate: open /var/serving-cert/tls.crt: permission denied
```

**Comment by naumannt** [comment]
We noticed that the "annotations"-section of the service account isn't updated by the `oc adm policy` command; `oc export sa webconsole` returned:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"openshift-web-console"},"name":"webconsole","namespace":"openshift-web-console"}}
  creationTimestamp: null
  labels:
    app: openshift-web-console
  name: webconsole
```
I edited it via `oc edit sa webconsole` and added "restricted" in there:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{"restricted"},"labels":{"app":"openshift-web-console"},"name":"webconsole","namespace":"openshift-web-console"}}
  creationTimestamp: null
  labels:
    app: openshift-web-console
  name: webconsole
```
Update: `oc get rolebindings` now correctly displays that `webconsole` is `restricted`. problem should no longer steam from that direction.
Sadly still same error loop.
